### PR TITLE
feature: Check if /var/log files/folders have sufficient permissions set

### PR DESCRIPTION
**Pull request by x10an14**

### CODE REVIEW

**Comment by x10an14** [comment]
@toby1knby / @mortenlj - Any inputs?

**Review by mortenlj — COMMENTED** [review]
I don't know how these are made into checks by Kolide, but would it make sense to write the query in such a way that it only returns invalid entries?

Ie. when the query returns 0 rows, everything is fine, if it returns rows, then every row is a failing file?

**Comment by x10an14** [comment]
> I don't know how these are made into checks by Kolide, but would it make sense to write the query in such a way that it only returns invalid entries?
> 
> Ie. when the query returns 0 rows, everything is fine, if it returns rows, then every row is a failing file?

Don't think that's a high priority, but it's not a bad suggestion =)
When I (or someone else) get a chance to test the below code-snippet, we could replace the SQL with it:
```sql
SELECT                                                                                                                  
        mode as 'permission octals',                                                                                    
        path                                                                                                            
FROM                                                                                                                    
        file                                                                                                            
WHERE                                                                                                                   
        type = 'regular'                                                                                                
AND                                                                                                                     
        path like '/var/log/%%'                                                                                         
AND (                                                                                                                   
        mode like '%00'                                                                                                 
        OR                                                                                                              
        mode like '%40'                                                                                                 
);                                                                                                                      
-- This is only okay if permissions match regex: "\d{1,2}[04]0" 
```

**Comment by x10an14** [comment]
Closed in favor of #7

**Pull request closed without merging**
