### PR TITLE
add system file permissions check

### PR DESCRIPTION
**Pull request by sechmann**
Alternate way of checking files, with mode check.

Example output for file with wrong mode
```
+-----------------+-----------+-----------+--------------------------+
| file_path       | uid_match | gid_match | mode_match               |
+-----------------+-----------+-----------+--------------------------+
| /etc/cron.allow | 0 = 0     | 0 = 0     | 0644 != 0[0-6][0-4][0-0] |
+-----------------+-----------+-----------+--------------------------+
```

### CODE REVIEW

**Comment by x10an14** [comment]
@Sechmann I merged in suggestion from Slack partner, whaddayathink? I thin kit looks good now tbh.

**Comment by sechmann** [comment]
Looks good

**Comment by sechmann** [comment]
I take it back, i think maybe letting users have read permissions on some of these files is OK, and CIS is too strict here (i had modified this in the pre-merge file table)

I have the default values on a fresh Ubuntu install, requiring every developer to change these permissions seems like a hassle for a very minor  security gain. Not worth it.

```
+---------------------+------------+------+----------+-----+---------+-----+-----------+-----------+-----------+--------+
| path                | mtime      | mode | mode_req | uid | uid_req | gid | groupname | gid_req_1 | gid_req_2 | cis_id |
+---------------------+------------+------+----------+-----+---------+-----+-----------+-----------+-----------+--------+
| /boot/grub/grub.cfg | 1611231338 | 0755 | 0400     | 0   | 0       | 0   | root      | root      |           | 1.5.1  |
| /etc/crontab        | 1581626682 | 0644 | 0600     | 0   | 0       | 0   | root      | root      |           | 5.1.2  |
| /etc/cron.hourly    | 1603375183 | 0755 | 0700     | 0   | 0       | 0   | root      | root      |           | 5.1.3  |
| /etc/cron.daily     | 1611225255 | 0755 | 0700     | 0   | 0       | 0   | root      | root      |           | 5.1.4  |
| /etc/cron.weekly    | 1603375800 | 0755 | 0700     | 0   | 0       | 0   | root      | root      |           | 5.1.5  |
| /etc/cron.monthly   | 1603375750 | 0755 | 0700     | 0   | 0       | 0   | root      | root      |           | 5.1.6  |
| /etc/cron.d         | 1611225444 | 0755 | 0700     | 0   | 0       | 0   | root      | root      |           | 5.1.7  |
| /etc/cron.allow     | 1611072342 | 0644 | 0640     | 0   | 0       | 0   | root      | root      |           | 5.1.8  |
| /etc/passwd-        | 1610438265 | 0644 | 0600     | 0   | 0       | 0   | root      | root      |           | 6.1.6  |
+---------------------+------------+------+----------+-----+---------+-----+-----------+-----------+-----------+--------+
```

**Comment by x10an14** [comment]
> I have the default values on a fresh Ubuntu install, requiring every developer to change these permissions seems like a hassle for a very minor security gain. Not worth it.

I see your point, and only disagree on one point:
>  i think maybe letting users have read permissions on some of these files is OK

But it's other/all users bit-octal you're discussing here, no? Doesn't that open it up for extraction by other processes on the machine? Like you and I discussed previously? Eg., subverted/malicious/broken system-user collecting hashed pw's from `/etc/passwd-` (the `passwd` tempfile used by `shadow`).

In summary, I'd argue that I think it's acceptable to have "one-off" changes like this, when we present the users as good feedback as we intend (where they can basically copy/paste commands).

EDIT: I'll commit your suggested changes to the rest of the files, but I'd like to discuss the above (one-off changes cost) with you.

**Comment by x10an14** [comment]
Summary from discussion today:
> passwd- and cron* files can remain as-is, @Sechmann feels that the CIS limitation recommendations are akin to "empty benefits" (and I can't think of good enough arguments otherwise myself).

`grub.cfg` file still needs some research, but (at the time of discussion) seems more like there may be good reasons we might agree with CIS of why it should be unreadable/not executable by others.

**Comment by sechmann** [comment]
After some research it seems like the only "secret" in grub config is an optional hashed password. If a user wants to harden their system beyond what we require i think it's reasonable to also let them decide whether the grub config should be readable/executable by group/other or not.

**Pull request merged**
